# Generated by Django 4.1.1 on 2022-10-04 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('anios', models.DateTimeField(verbose_name='Anio de lanzamiento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.usuarios')),
            ],
        ),
    ]
