# Generated by Django 4.1.1 on 2022-10-06 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_peliculas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='peliculas',
            new_name='Tarea',
        ),
        migrations.RenameModel(
            old_name='usuarios',
            new_name='Usuario',
        ),
    ]
