# Generated by Django 4.1.1 on 2022-10-07 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0003_rename_peliculas_tarea_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarea',
            new_name='peliculas',
        ),
        migrations.RenameModel(
            old_name='Usuario',
            new_name='usuarios',
        ),
    ]
