# Generated by Django 4.1.1 on 2022-10-07 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0004_rename_tarea_peliculas_rename_usuario_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTarea', models.CharField(max_length=60)),
                ('estado', models.BooleanField(default=False)),
                ('incio', models.DateTimeField(verbose_name='Dia de inicio')),
                ('finalizar', models.DateTimeField(verbose_name='Plazo maximo')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=15)),
                ('dia_registro', models.DateTimeField(verbose_name='Dia registro')),
            ],
        ),
        migrations.DeleteModel(
            name='peliculas',
        ),
        migrations.DeleteModel(
            name='usuarios',
        ),
        migrations.AddField(
            model_name='tarea',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagina.usuario'),
        ),
    ]
